### ISSUE TITLE
Warning coming from material-ui

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-client#2]
Use of the select boxes in Formik with Material-UI such as this:
```
                <Field
                    component={TextField}
                    type="text"
                    name="type"
                    label="Type"
                    fullWidth 
                    disabled={false}
                    select={true}
                    SelectProps={{
                        multiple: false,
                    }}
                >
                    <MenuItem value="OTU">OTU</MenuItem>
                    <MenuItem value="specimen">Specimen</MenuItem>
                </Field>
```
is throwing the following warning:
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.
```
This is a problem with the third party modules, not our code. This stackoverflow issue suggests it is solved in material-ui V5:
https://stackoverflow.com/questions/61220424/material-ui-drawer-finddomnode-is-deprecated-in-strictmode.

The problem with that is that, with V5, Material-UI changed to MUI (https://mui.com/blog/material-ui-is-now-mui/) and it is not clear what effect this will have on our use of formik-material-ui, which currently requires V4. 

Since this is just a warning, I think we can ignore it for now.  I'm opening this issue to document our awareness of the problem.

**Comment by aazaff** [comment]
This was indirectly fixed by other commits.

**Comment by NoisyFlowers** [comment]
We've now migrated to MUI v5 and this issue has gone away.
