### ISSUE TITLE
the mini search forms are just blank when no hits are found

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-client#23]
There should be a message stating that no results were found, and probably a button to reset back the search option.

![image](https://github.com/paleobot/pbot-client/assets/10422595/70d2e868-2a18-483d-9d98-6940addb6414)

**Comment by NoisyFlowers** [comment]
This is in bf878a9ef67b79d3d74c17558df4d2fb330e74ea

Merged to master and running on dev and stage
