### ISSUE TITLE
Consider moving form select components into related element folder

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-client#3]
Any place a specific node must be selected in a form, there is React component logic for querying the db and building JSX from the result. This is duplicated in some files. 

Look into moving these components into the directory for that element type (e.g. DescriptionSelect into the Description directory).

This would have to provide a means for passing filter params to the query and any required logic for the onChange handler.

**Comment by aazaff** [comment]
@NoisyFlowers has already started doing this. No need for an issue to track it.
