### ISSUE TITLE
There is no way to cancel registration and go back to login

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-client#4]
![Screenshot 2022-03-01 at 10 27 01 AM](https://user-images.githubusercontent.com/10422595/156218929-95034639-79e8-40e5-bdfa-5119bc6ab950.png)

I changed my mind and just want to login.

**Comment by aazaff** [comment]
To be clear this is fixably just by doing a hard refresh of the browser, but is nevertheless an oversight on our part.

**Comment by NoisyFlowers** [comment]
This is in a9f8eab798665166e8fe47381079d59800cbf89e.
