### ISSUE TITLE
Change groups user addition from picklist to type-ahead/picklist hybrid

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-client#5]
Low priority change.

**Comment by aazaff** [comment]
We decided to hold off on this because it was a huge hassle and wasn't needed atm.

**Comment by NoisyFlowers** [comment]
Now that we're on MUI v5, I'm going to take another look at this. There is an Autocomplete component that looks promising.

**Comment by NoisyFlowers** [comment]
This proposed change is now obviated by our use of a search form for users.
