### ISSUE TITLE
Changes to Group Behavior in Client

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-client#7]
1. Filter out guest
2. Filter out self (User is automatically added to group, therefore no need to select)
3. Don't show all Person nodes - only show Person nodes with password (i.e., users)
4. Verify that a user cannot see/edit a group they are not part of group
5. Add generic message when no results are found - something like, "No public results were found."
6. Let you query BY group - i.e., see all items in a group. API and Client change required

**Comment by NoisyFlowers** [comment]
1 and 3 are in commit ce72bfbd47a370eb9758e05bfb8e4180536d74bf. 3 also required api commit 9f5201551693e71e0027e960439a7781354d3eeb.

2 is in fc379956b20de17760fdc558171aa5b5e9e510cd.

4 is verified.

5 is in 39bd2bbc02fce2581c85b14b9159a1fb3d73b42f and further refined in 1b569e893469be6c0dbc2005a20cd82317a6b2c7, eee6b3aa1fe8ceb3ceaf153d2df466cdb01dd20c, e39ed8b1cc1926e85d21c56d5c8cd08366dc67e6, 9561a82b205e1b79a179a06d7ae5d9cfe08fcc73, and 89af270680e259015fde0455137295334dcf835c.

6 is in in 1b569e893469be6c0dbc2005a20cd82317a6b2c7, eee6b3aa1fe8ceb3ceaf153d2df466cdb01dd20c, e39ed8b1cc1926e85d21c56d5c8cd08366dc67e6, 9561a82b205e1b79a179a06d7ae5d9cfe08fcc73, and 89af270680e259015fde0455137295334dcf835c.
